apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
      - name: registration-app
        image: haftuabadi/registration-app:latest
        ports:
        - containerPort: 80

