apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # use ClusterIP if you don't need external access

